# Generated by Django 2.2 on 2020-02-27 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('play_ground', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contestant',
            old_name='full_name',
            new_name='display_name',
        ),
    ]
