# Generated by Django 2.2 on 2020-02-27 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play_ground', '0002_auto_20200227_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestant',
            name='track',
            field=models.CharField(default='Machine learning', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contestant',
            name='display_name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='contestant',
            name='email',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='contestant',
            name='twitter_handle',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
