# Generated by Django 2.2 on 2020-02-27 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('play_ground', '0003_auto_20200227_1859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contestant',
            name='display_name',
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet', models.CharField(max_length=100)),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('twitter_handle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='play_ground.Contestant')),
            ],
            options={
                'verbose_name_plural': 'Tweets',
                'db_table': 'tweets',
            },
        ),
    ]
