# Generated by Django 2.2 on 2020-02-27 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play_ground', '0004_auto_20200227_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='user',
            field=models.CharField(default='19qskwu0pd38m36ydpn7', max_length=50),
        ),
    ]
