# Generated by Django 2.2 on 2020-02-28 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('play_ground', '0005_tweet_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='user',
        ),
    ]
