# Generated by Django 2.2 on 2020-02-28 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('play_ground', '0007_contestant_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contestant',
            name='track',
        ),
    ]
