# Generated by Django 2.2 on 2020-03-02 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play_ground', '0009_auto_20200302_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='tweet',
            field=models.TextField(blank=True),
        ),
    ]
